package com.atm.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks: 银行卡信息表
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table bank_card_info
 */
public class BankCardInfo implements Serializable {
	/**
	 * Database Column Remarks: 19位银行卡id
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_card_id
	 *
	 * @mbg.generated
	 */
	private String bankCardId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.user_id
	 *
	 * @mbg.generated
	 */
	private String userId;

	/**
	 * Database Column Remarks: 银行卡6位密码
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_card_password
	 *
	 * @mbg.generated
	 */
	private String bankCardPassword;

	/**
	 * Database Column Remarks: 开户时间戳
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_gmt_create
	 *
	 * @mbg.generated
	 */
	private Long bankGmtCreate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_money
	 *
	 * @mbg.generated
	 */
	private BigDecimal bankMoney;

	/**
	 * Database Column Remarks: 1为储蓄卡2为信用卡
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_type
	 *
	 * @mbg.generated
	 */
	private Integer bankType;

	/**
	 * Database Column Remarks: 卡类型为2时才会有透支额度储蓄用户为0
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_credit_limit
	 *
	 * @mbg.generated
	 */
	private BigDecimal bankCreditLimit;

	/**
	 * Database Column Remarks: 1表示开通0表没有开通
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_message
	 *
	 * @mbg.generated
	 */
	private Integer bankMessage;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_transactor
	 *
	 * @mbg.generated
	 */
	private String bankTransactor;

	/**
	 * Database Column Remarks: 1 正常 2 注销 3 异常 4冻结
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_card_status
	 *
	 * @mbg.generated
	 */
	private Integer bankCardStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_overdue_month
	 *
	 * @mbg.generated
	 */
	private Integer bankOverdueMonth;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_card_info.bank_overdue_amount
	 *
	 * @mbg.generated
	 */
	private BigDecimal bankOverdueAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table bank_card_info
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_card_id
	 *
	 * @return the value of bank_card_info.bank_card_id
	 *
	 * @mbg.generated
	 */
	public String getBankCardId() {
		return bankCardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_card_id
	 *
	 * @param bankCardId
	 *            the value for bank_card_info.bank_card_id
	 *
	 * @mbg.generated
	 */
	public void setBankCardId(String bankCardId) {
		this.bankCardId = bankCardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.user_id
	 *
	 * @return the value of bank_card_info.user_id
	 *
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.user_id
	 *
	 * @param userId
	 *            the value for bank_card_info.user_id
	 *
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_card_password
	 *
	 * @return the value of bank_card_info.bank_card_password
	 *
	 * @mbg.generated
	 */
	public String getBankCardPassword() {
		return bankCardPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_card_password
	 *
	 * @param bankCardPassword
	 *            the value for bank_card_info.bank_card_password
	 *
	 * @mbg.generated
	 */
	public void setBankCardPassword(String bankCardPassword) {
		this.bankCardPassword = bankCardPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_gmt_create
	 *
	 * @return the value of bank_card_info.bank_gmt_create
	 *
	 * @mbg.generated
	 */
	public Long getBankGmtCreate() {
		return bankGmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_gmt_create
	 *
	 * @param bankGmtCreate
	 *            the value for bank_card_info.bank_gmt_create
	 *
	 * @mbg.generated
	 */
	public void setBankGmtCreate(Long bankGmtCreate) {
		this.bankGmtCreate = bankGmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_money
	 *
	 * @return the value of bank_card_info.bank_money
	 *
	 * @mbg.generated
	 */
	public BigDecimal getBankMoney() {
		return bankMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_money
	 *
	 * @param bankMoney
	 *            the value for bank_card_info.bank_money
	 *
	 * @mbg.generated
	 */
	public void setBankMoney(BigDecimal bankMoney) {
		this.bankMoney = bankMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_type
	 *
	 * @return the value of bank_card_info.bank_type
	 *
	 * @mbg.generated
	 */
	public Integer getBankType() {
		return bankType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_type
	 *
	 * @param bankType
	 *            the value for bank_card_info.bank_type
	 *
	 * @mbg.generated
	 */
	public void setBankType(Integer bankType) {
		this.bankType = bankType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_credit_limit
	 *
	 * @return the value of bank_card_info.bank_credit_limit
	 *
	 * @mbg.generated
	 */
	public BigDecimal getBankCreditLimit() {
		return bankCreditLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_credit_limit
	 *
	 * @param bankCreditLimit
	 *            the value for bank_card_info.bank_credit_limit
	 *
	 * @mbg.generated
	 */
	public void setBankCreditLimit(BigDecimal bankCreditLimit) {
		this.bankCreditLimit = bankCreditLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_message
	 *
	 * @return the value of bank_card_info.bank_message
	 *
	 * @mbg.generated
	 */
	public Integer getBankMessage() {
		return bankMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_message
	 *
	 * @param bankMessage
	 *            the value for bank_card_info.bank_message
	 *
	 * @mbg.generated
	 */
	public void setBankMessage(Integer bankMessage) {
		this.bankMessage = bankMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_transactor
	 *
	 * @return the value of bank_card_info.bank_transactor
	 *
	 * @mbg.generated
	 */
	public String getBankTransactor() {
		return bankTransactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_transactor
	 *
	 * @param bankTransactor
	 *            the value for bank_card_info.bank_transactor
	 *
	 * @mbg.generated
	 */
	public void setBankTransactor(String bankTransactor) {
		this.bankTransactor = bankTransactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_card_status
	 *
	 * @return the value of bank_card_info.bank_card_status
	 *
	 * @mbg.generated
	 */
	public Integer getBankCardStatus() {
		return bankCardStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_card_status
	 *
	 * @param bankCardStatus
	 *            the value for bank_card_info.bank_card_status
	 *
	 * @mbg.generated
	 */
	public void setBankCardStatus(Integer bankCardStatus) {
		this.bankCardStatus = bankCardStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_overdue_month
	 *
	 * @return the value of bank_card_info.bank_overdue_month
	 *
	 * @mbg.generated
	 */
	public Integer getBankOverdueMonth() {
		return bankOverdueMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_overdue_month
	 *
	 * @param bankOverdueMonth
	 *            the value for bank_card_info.bank_overdue_month
	 *
	 * @mbg.generated
	 */
	public void setBankOverdueMonth(Integer bankOverdueMonth) {
		this.bankOverdueMonth = bankOverdueMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_card_info.bank_overdue_amount
	 *
	 * @return the value of bank_card_info.bank_overdue_amount
	 *
	 * @mbg.generated
	 */
	public BigDecimal getBankOverdueAmount() {
		return bankOverdueAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_card_info.bank_overdue_amount
	 *
	 * @param bankOverdueAmount
	 *            the value for bank_card_info.bank_overdue_amount
	 *
	 * @mbg.generated
	 */
	public void setBankOverdueAmount(BigDecimal bankOverdueAmount) {
		this.bankOverdueAmount = bankOverdueAmount;
	}
}