package com.atm.pojo;

import java.io.Serializable;

/**
 * Database Table Remarks: 记录银行客户的详细信息
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table bank_user_detail
 */
public class BankUserDetail implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_detail.user_id
	 *
	 * @mbg.generated
	 */
	private String userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_detail.user_password
	 *
	 * @mbg.generated
	 */
	private String userPassword;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_detail.username
	 *
	 * @mbg.generated
	 */
	private String username;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_detail.user_phone_num
	 *
	 * @mbg.generated
	 */
	private String userPhoneNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_detail.user_email
	 *
	 * @mbg.generated
	 */
	private String userEmail;

	/**
	 * Database Column Remarks: 1正常 2异常 3冻结
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_detail.user_status
	 *
	 * @mbg.generated
	 */
	private Integer userStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_detail.user_card_count
	 *
	 * @mbg.generated
	 */
	private Integer userCardCount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table bank_user_detail
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_detail.user_id
	 *
	 * @return the value of bank_user_detail.user_id
	 *
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_detail.user_id
	 *
	 * @param userId
	 *            the value for bank_user_detail.user_id
	 *
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_detail.user_password
	 *
	 * @return the value of bank_user_detail.user_password
	 *
	 * @mbg.generated
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_detail.user_password
	 *
	 * @param userPassword
	 *            the value for bank_user_detail.user_password
	 *
	 * @mbg.generated
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_detail.username
	 *
	 * @return the value of bank_user_detail.username
	 *
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_detail.username
	 *
	 * @param username
	 *            the value for bank_user_detail.username
	 *
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_detail.user_phone_num
	 *
	 * @return the value of bank_user_detail.user_phone_num
	 *
	 * @mbg.generated
	 */
	public String getUserPhoneNum() {
		return userPhoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_detail.user_phone_num
	 *
	 * @param userPhoneNum
	 *            the value for bank_user_detail.user_phone_num
	 *
	 * @mbg.generated
	 */
	public void setUserPhoneNum(String userPhoneNum) {
		this.userPhoneNum = userPhoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_detail.user_email
	 *
	 * @return the value of bank_user_detail.user_email
	 *
	 * @mbg.generated
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_detail.user_email
	 *
	 * @param userEmail
	 *            the value for bank_user_detail.user_email
	 *
	 * @mbg.generated
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_detail.user_status
	 *
	 * @return the value of bank_user_detail.user_status
	 *
	 * @mbg.generated
	 */
	public Integer getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_detail.user_status
	 *
	 * @param userStatus
	 *            the value for bank_user_detail.user_status
	 *
	 * @mbg.generated
	 */
	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_detail.user_card_count
	 *
	 * @return the value of bank_user_detail.user_card_count
	 *
	 * @mbg.generated
	 */
	public Integer getUserCardCount() {
		return userCardCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_detail.user_card_count
	 *
	 * @param userCardCount
	 *            the value for bank_user_detail.user_card_count
	 *
	 * @mbg.generated
	 */
	public void setUserCardCount(Integer userCardCount) {
		this.userCardCount = userCardCount;
	}
}