package com.atm.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks: 银行客户基础信息表
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table bank_user_info
 */
public class BankUserInfo implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_info.user_id
	 *
	 * @mbg.generated
	 */
	private String userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_info.username
	 *
	 * @mbg.generated
	 */
	private String username;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_info.user_identify
	 *
	 * @mbg.generated
	 */
	private String userIdentify;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_info.timestamp
	 *
	 * @mbg.generated
	 */
	private Date timestamp;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_info.bank_transactor
	 *
	 * @mbg.generated
	 */
	private String bankTransactor;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_user_info.user_address
	 *
	 * @mbg.generated
	 */
	private String userAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table bank_user_info
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_info.user_id
	 *
	 * @return the value of bank_user_info.user_id
	 *
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_info.user_id
	 *
	 * @param userId
	 *            the value for bank_user_info.user_id
	 *
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_info.username
	 *
	 * @return the value of bank_user_info.username
	 *
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_info.username
	 *
	 * @param username
	 *            the value for bank_user_info.username
	 *
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_info.user_identify
	 *
	 * @return the value of bank_user_info.user_identify
	 *
	 * @mbg.generated
	 */
	public String getUserIdentify() {
		return userIdentify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_info.user_identify
	 *
	 * @param userIdentify
	 *            the value for bank_user_info.user_identify
	 *
	 * @mbg.generated
	 */
	public void setUserIdentify(String userIdentify) {
		this.userIdentify = userIdentify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_info.timestamp
	 *
	 * @return the value of bank_user_info.timestamp
	 *
	 * @mbg.generated
	 */
	public Date getTimestamp() {
		return timestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_info.timestamp
	 *
	 * @param timestamp
	 *            the value for bank_user_info.timestamp
	 *
	 * @mbg.generated
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_info.bank_transactor
	 *
	 * @return the value of bank_user_info.bank_transactor
	 *
	 * @mbg.generated
	 */
	public String getBankTransactor() {
		return bankTransactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_info.bank_transactor
	 *
	 * @param bankTransactor
	 *            the value for bank_user_info.bank_transactor
	 *
	 * @mbg.generated
	 */
	public void setBankTransactor(String bankTransactor) {
		this.bankTransactor = bankTransactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_user_info.user_address
	 *
	 * @return the value of bank_user_info.user_address
	 *
	 * @mbg.generated
	 */
	public String getUserAddress() {
		return userAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_user_info.user_address
	 *
	 * @param userAddress
	 *            the value for bank_user_info.user_address
	 *
	 * @mbg.generated
	 */
	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}
}