package com.atm.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table bank_exchange_rate
 */
public class BankExchangeRate implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_exchange_rate.currency
	 *
	 * @mbg.generated
	 */
	private String currency;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_exchange_rate.RMB
	 *
	 * @mbg.generated
	 */
	private BigDecimal rmb;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_exchange_rate.USD
	 *
	 * @mbg.generated
	 */
	private BigDecimal usd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_exchange_rate.EUR
	 *
	 * @mbg.generated
	 */
	private BigDecimal eur;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_exchange_rate.GBP
	 *
	 * @mbg.generated
	 */
	private BigDecimal gbp;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bank_exchange_rate.CHF
	 *
	 * @mbg.generated
	 */
	private BigDecimal chf;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table bank_exchange_rate
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_exchange_rate.currency
	 *
	 * @return the value of bank_exchange_rate.currency
	 *
	 * @mbg.generated
	 */
	public String getCurrency() {
		return currency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_exchange_rate.currency
	 *
	 * @param currency
	 *            the value for bank_exchange_rate.currency
	 *
	 * @mbg.generated
	 */
	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_exchange_rate.RMB
	 *
	 * @return the value of bank_exchange_rate.RMB
	 *
	 * @mbg.generated
	 */
	public BigDecimal getRmb() {
		return rmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_exchange_rate.RMB
	 *
	 * @param rmb
	 *            the value for bank_exchange_rate.RMB
	 *
	 * @mbg.generated
	 */
	public void setRmb(BigDecimal rmb) {
		this.rmb = rmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_exchange_rate.USD
	 *
	 * @return the value of bank_exchange_rate.USD
	 *
	 * @mbg.generated
	 */
	public BigDecimal getUsd() {
		return usd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_exchange_rate.USD
	 *
	 * @param usd
	 *            the value for bank_exchange_rate.USD
	 *
	 * @mbg.generated
	 */
	public void setUsd(BigDecimal usd) {
		this.usd = usd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_exchange_rate.EUR
	 *
	 * @return the value of bank_exchange_rate.EUR
	 *
	 * @mbg.generated
	 */
	public BigDecimal getEur() {
		return eur;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_exchange_rate.EUR
	 *
	 * @param eur
	 *            the value for bank_exchange_rate.EUR
	 *
	 * @mbg.generated
	 */
	public void setEur(BigDecimal eur) {
		this.eur = eur;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_exchange_rate.GBP
	 *
	 * @return the value of bank_exchange_rate.GBP
	 *
	 * @mbg.generated
	 */
	public BigDecimal getGbp() {
		return gbp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_exchange_rate.GBP
	 *
	 * @param gbp
	 *            the value for bank_exchange_rate.GBP
	 *
	 * @mbg.generated
	 */
	public void setGbp(BigDecimal gbp) {
		this.gbp = gbp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bank_exchange_rate.CHF
	 *
	 * @return the value of bank_exchange_rate.CHF
	 *
	 * @mbg.generated
	 */
	public BigDecimal getChf() {
		return chf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bank_exchange_rate.CHF
	 *
	 * @param chf
	 *            the value for bank_exchange_rate.CHF
	 *
	 * @mbg.generated
	 */
	public void setChf(BigDecimal chf) {
		this.chf = chf;
	}
}