package com.atm.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.atm.pojo.BankUserDetail;

@Mapper
public interface BankUserDetailMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_detail
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_detail
	 *
	 * @mbg.generated
	 */
	int insert(BankUserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_detail
	 *
	 * @mbg.generated
	 */
	int insertSelective(BankUserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_detail
	 *
	 * @mbg.generated
	 */
	BankUserDetail selectByPrimaryKey(String userId);

	BankUserDetail selectByUNAndPWD(BankUserDetail bankUserDetail);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_detail
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(BankUserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_detail
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(BankUserDetail record);
}