package com.atm.mapper;

import com.atm.pojo.BankExchangeRate;

public interface BankExchangeRateMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_exchange_rate
	 *
	 * @mbg.generated
	 */
	int insert(BankExchangeRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_exchange_rate
	 *
	 * @mbg.generated
	 */
	int insertSelective(BankExchangeRate record);
}