package com.atm.mapper;

import com.atm.pojo.BankTransDetail;

public interface BankTransDetailMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_trans_detail
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long bankSerialNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_trans_detail
	 *
	 * @mbg.generated
	 */
	int insert(BankTransDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_trans_detail
	 *
	 * @mbg.generated
	 */
	int insertSelective(BankTransDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_trans_detail
	 *
	 * @mbg.generated
	 */
	BankTransDetail selectByPrimaryKey(Long bankSerialNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_trans_detail
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(BankTransDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_trans_detail
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(BankTransDetail record);
}