package com.atm.mapper;

import com.atm.pojo.BankUserInfo;

public interface BankUserInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_info
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_info
	 *
	 * @mbg.generated
	 */
	int insert(BankUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_info
	 *
	 * @mbg.generated
	 */
	int insertSelective(BankUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_info
	 *
	 * @mbg.generated
	 */
	BankUserInfo selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(BankUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_user_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(BankUserInfo record);
}